meta_site_name: "TechZenith"
meta_title: "TechZenith"
meta_type: "website"
meta_description: ""
meta_published_time: ""
meta_modified_time: ""
meta_keywords: ""
meta_image: "/media/images/cover/cover.PNG"  # Une image dans votre dossier app/assets/images/
twitter_account: "@stagiairesoff"